### ISSUE TITLE
code correct but would like an explanation of it :)

### ISSUE THREAD

**Issue by basharaq** [Farahobaidat/assignment-10#5]
https://github.com/Farahobaidat/assignment-10/blob/db5cad1c11d1fe4992c84b6a26a7fd60f69a7b0d/task7/task7.js#L1

can you explain the principle of how this code works? it looks very similar to code on the internet so i just want to make sure you understand it ;)

**Comment by Farahobaidat** [comment]
we need counter to count time of  frequent so i  defined count variable but this variable count all time when element from loop one equal with loop 2 so i need sec variable to save most time for element from loop 1 when out from loop 2 and transfer to element 2 in loop 1 counter return to zero to count frequent time for element 2  i hope i could explain that
😅
